services:
  backend:
    build:
      context: ./app
      dockerfile: backend/Dockerfile
    ports:
      - "5000:5000"
    environment:
      - GRPC_PORT=5000
    networks:
      - fair-market-network
    healthcheck:
      test: ["CMD", "node", "-e", "console.log('Backend health check')"]
      interval: 30s
      timeout: 10s
      retries: 3

  middleware:
    build:
      context: ./app
      dockerfile: middleware/Dockerfile
    ports:
      - "4000:3001"
    environment:
      - PORT=3001
      - GRPC_HOST=backend:5000
    depends_on:
      - backend
    networks:
      - fair-market-network
    healthcheck:
      test: ["CMD", "wget", "--no-verbose", "--tries=1", "--spider", "http://localhost:3001/health"]
      interval: 30s
      timeout: 10s
      retries: 3

  frontend:
    build:
      context: ./app
      dockerfile: frontend/Dockerfile
    ports:
      - "3000:80"
    environment:
      - NEXT_PUBLIC_API_BASE_URL=http://localhost:4000
    depends_on:
      - middleware
    networks:
      - fair-market-network
    healthcheck:
      test: ["CMD", "wget", "--no-verbose", "--tries=1", "--spider", "http://localhost:80"]
      interval: 30s
      timeout: 10s
      retries: 3

networks:
  fair-market-network:
    driver: bridge
